apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
  namespace: clawpurse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain-service
  template:
    metadata:
      labels:
        app: blockchain-service
    spec:
      containers:
      - name: blockchain
        image: clawpurse/blockchain-service:latest
        ports:
        - containerPort: 8080
